name: Run Tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install meson
        run: sudo apt-get install python3 python3-pip python3-setuptools python3-wheel ninja-build
      - name: Build
        run: meson build
      - name: compile and test
        run: cd build/ && meson compile && meson test