name: Run Tests
on: [push]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Installing requried packages for meson
        run: sudo apt-get install python3 python3-pip python3-setuptools python3-wheel ninja-build
      - name: Installing meson
        run: pip3 install --user meson
      - name: Build
        run: meson build
      - name: compile and test
        working-directory: ./build
        run: >-
            meson compile;
            meson test;
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Installing requried packages for meson
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Installing meson
        run: pip3 install meson
      - name: Build
        run: meson build
      - name: compile 
        working-directory: ./build
        run: meson compile
      - name: test
        working-directory: ./build
        run: meson test
